# Generated by Django 3.1.1 on 2021-02-05 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ijambo', '0009_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteulyrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musiclyrics', to='ijambo.music'),
        ),
    ]
