# Generated by Django 3.1.1 on 2021-02-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ijambo', '0010_auto_20210205_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albummusic',
            unique_together={('albumSong', 'music')},
        ),
    ]
